import type { AppliedCredentials } from '../auth/upstream';
import { NetworkPolicyError, ResponseTooLargeError, readCapped, safeFetch } from '../net';
import type { CallToolResult, ContentBlock, JsonSchema, JsonValue, ToolDefinition } from '../types';
import {
	applyPathTemplate,
	joinUrl,
	serializeHeaderParam,
	serializePathParam,
	serializeQueryParam
} from './params';

export interface CallOptions {
	timeoutMs?: number;
	maxResponseBytes?: number;
	credentialHosts?: Set<string>;
	exemptHosts?: Set<string>;
	signal?: AbortSignal;
}

const DEFAULT_MAX_RESPONSE = 2 * 1024 * 1024;
const MAX_ERROR_BODY = 4000;
const MAX_TEXT_RESULT = 512 * 1024;

export interface PreparedRequest {
	url: string;
	method: string;
	headers: Record<string, string>;
	body?: BodyInit;
}

function toBase64(bytes: Uint8Array): string {
	let binary = '';
	const chunk = 0x8000;
	for (let i = 0; i < bytes.length; i += chunk) {
		binary += String.fromCharCode(...bytes.subarray(i, i + chunk));
	}
	return btoa(binary);
}

function fromBase64(value: string): Uint8Array {
	const binary = atob(value);
	const out = new Uint8Array(binary.length);
	for (let i = 0; i < binary.length; i++) out[i] = binary.charCodeAt(i);
	return out;
}

function encodeBody(
	value: unknown,
	contentType: string
): { body: BodyInit; contentType: string } | undefined {
	if (value === undefined) return undefined;

	const base = contentType.split(';')[0]?.trim().toLowerCase() ?? 'application/json';

	if (base === 'application/x-www-form-urlencoded') {
		const params = new URLSearchParams();
		if (value && typeof value === 'object' && !Array.isArray(value)) {
			for (const [k, v] of Object.entries(value as Record<string, unknown>)) {
				if (v === undefined || v === null) continue;
				if (Array.isArray(v)) v.forEach((item) => params.append(k, String(item)));
				else params.append(k, typeof v === 'object' ? JSON.stringify(v) : String(v));
			}
		}
		return { body: params.toString(), contentType: base };
	}

	if (base === 'multipart/form-data') {
		const form = new FormData();
		if (value && typeof value === 'object' && !Array.isArray(value)) {
			for (const [k, v] of Object.entries(value as Record<string, unknown>)) {
				if (v === undefined || v === null) continue;
				if (typeof v === 'string' && /^[A-Za-z0-9+/]+={0,2}$/.test(v) && v.length > 64) {
					// a long base64 string in a multipart field is a file, not a literal value
					const bytes = fromBase64(v);
					form.append(k, new Blob([bytes.buffer as ArrayBuffer]), k);
				} else {
					form.append(k, typeof v === 'object' ? JSON.stringify(v) : String(v));
				}
			}
		}
		// the boundary is generated by fetch, so the caller must not set Content-Type
		return { body: form, contentType: '' };
	}

	if (
		base === 'application/octet-stream' ||
		base.startsWith('image/') ||
		base.startsWith('audio/')
	) {
		if (typeof value === 'string') {
			try {
				return { body: fromBase64(value) as unknown as BodyInit, contentType: base };
			} catch {
				return { body: value, contentType: base };
			}
		}
		return { body: JSON.stringify(value), contentType: base };
	}

	if (base.startsWith('text/') || base === 'application/xml' || base === 'text/xml') {
		return { body: typeof value === 'string' ? value : JSON.stringify(value), contentType: base };
	}

	return { body: JSON.stringify(value), contentType: base || 'application/json' };
}

/**
 * Turns tool arguments into a concrete HTTP request using the bindings recorded when the tool
 * was generated, so no argument name has to be parsed to know where it belongs.
 */
export function prepareRequest(
	tool: ToolDefinition,
	args: Record<string, unknown>,
	baseUrl: string,
	credentials: AppliedCredentials
): PreparedRequest {
	const pathValues = new Map<string, string>();
	const queryPairs: string[] = [];
	const headers: Record<string, string> = {};
	const cookies: string[] = [];
	let bodyValue: unknown;
	let bodyContentType = tool.requestContentType ?? 'application/json';

	for (const [argName, binding] of Object.entries(tool.bindings)) {
		const value = args[argName];
		if (value === undefined) continue;

		switch (binding.in) {
			case 'path':
				pathValues.set(
					binding.name,
					serializePathParam(binding.name, value, {
						style: binding.style,
						explode: binding.explode
					})
				);
				break;
			case 'query':
				queryPairs.push(
					...serializeQueryParam(binding.name, value, {
						style: binding.style,
						explode: binding.explode
					})
				);
				break;
			case 'header':
				headers[binding.name] = serializeHeaderParam(value, { explode: binding.explode });
				break;
			case 'cookie':
				cookies.push(`${binding.name}=${serializeHeaderParam(value)}`);
				break;
			case 'body':
				bodyValue = value;
				if (binding.contentType) bodyContentType = binding.contentType;
				break;
		}
	}

	for (const [name, value] of Object.entries(credentials.query)) {
		queryPairs.push(`${encodeURIComponent(name)}=${encodeURIComponent(value)}`);
	}
	for (const [name, value] of Object.entries(credentials.cookies)) {
		cookies.push(`${name}=${value}`);
	}
	Object.assign(headers, credentials.headers);

	if (cookies.length > 0) {
		headers['Cookie'] = headers['Cookie']
			? `${headers['Cookie']}; ${cookies.join('; ')}`
			: cookies.join('; ');
	}

	const path = applyPathTemplate(tool.path, pathValues);
	const url = joinUrl(baseUrl, path) + (queryPairs.length ? `?${queryPairs.join('&')}` : '');

	const encoded =
		tool.method === 'GET' || tool.method === 'HEAD'
			? undefined
			: encodeBody(bodyValue, bodyContentType);

	if (encoded?.contentType) headers['Content-Type'] = encoded.contentType;
	if (!headers['Accept']) headers['Accept'] = 'application/json, text/plain;q=0.9, */*;q=0.8';

	return { url, method: tool.method, headers, body: encoded?.body };
}

/** shallow check that a value could satisfy the declared output schema */
function conformsShallow(value: unknown, schema: JsonSchema | undefined): boolean {
	if (!schema) return false;

	const declared = schema.type;
	const types = typeof declared === 'string' ? [declared] : Array.isArray(declared) ? declared : [];
	if (types.length === 0) return true;

	const actual =
		value === null
			? 'null'
			: Array.isArray(value)
				? 'array'
				: typeof value === 'number'
					? Number.isInteger(value)
						? 'integer'
						: 'number'
					: typeof value;

	if (actual === 'integer' && types.includes('number')) return true;
	return types.includes(actual);
}

function textBlock(text: string): ContentBlock {
	return { type: 'text', text };
}

function errorResult(message: string): CallToolResult {
	return { content: [textBlock(message)], isError: true };
}

/** the tool result plus the transport facts a caller may need, such as an async job pointer */
export interface CallOutcome {
	result: CallToolResult;
	status: number;
	location?: string;
	retryAfterMs?: number;
}

function outcome(result: CallToolResult, status = 0): CallOutcome {
	return { result, status };
}

/** Executes one tool call and maps the upstream response onto MCP content blocks. */
export async function executeCall(
	tool: ToolDefinition,
	args: Record<string, unknown>,
	baseUrl: string,
	credentials: AppliedCredentials,
	options: CallOptions = {}
): Promise<CallOutcome> {
	const limit = options.maxResponseBytes ?? DEFAULT_MAX_RESPONSE;

	let prepared: PreparedRequest;
	try {
		prepared = prepareRequest(tool, args, baseUrl, credentials);
	} catch (error) {
		return outcome(errorResult(`Could not build the request: ${describe(error)}`));
	}

	let response: Response;
	try {
		response = await safeFetch(
			prepared.url,
			{ method: prepared.method, headers: prepared.headers, body: prepared.body },
			{
				timeoutMs: options.timeoutMs ?? 30_000,
				credentialHosts: options.credentialHosts,
				exemptHosts: options.exemptHosts,
				signal: options.signal
			}
		);
	} catch (error) {
		if (error instanceof NetworkPolicyError) {
			return outcome(errorResult(`Request blocked by network policy: ${error.message}`));
		}
		if (error instanceof Error && error.name === 'AbortError') {
			return outcome(
				errorResult(
					`The API did not respond within the timeout (${prepared.method} ${prepared.url}).`
				)
			);
		}
		return outcome(errorResult(`Request to the API failed: ${describe(error)}`));
	}

	const status = response.status;
	const contentType = (response.headers.get('content-type') ?? '').toLowerCase();
	const base = contentType.split(';')[0]?.trim() ?? '';

	const location = response.headers.get('location') ?? undefined;
	const retryAfter = Number(response.headers.get('retry-after'));
	const retryAfterMs =
		Number.isFinite(retryAfter) && retryAfter > 0 ? retryAfter * 1000 : undefined;
	const meta = { status, location: location ?? undefined, retryAfterMs };

	if (status === 204 || status === 205) {
		return {
			result: { content: [textBlock(`${status} ${response.statusText || 'No Content'}`)] },
			...meta
		};
	}

	let bytes: Uint8Array;
	try {
		bytes = await readCapped(response, limit);
	} catch (error) {
		if (error instanceof ResponseTooLargeError) {
			return {
				result: errorResult(
					`The API returned more than ${limit} bytes. Narrow the request with filters or pagination.`
				),
				...meta
			};
		}
		return { result: errorResult(`Could not read the API response: ${describe(error)}`), ...meta };
	}

	if (!response.ok) {
		const preview = new TextDecoder().decode(bytes.subarray(0, MAX_ERROR_BODY));
		const suffix = bytes.byteLength > MAX_ERROR_BODY ? '\n... (truncated)' : '';
		return {
			result: {
				content: [
					textBlock(
						`${status} ${response.statusText} from ${prepared.method} ${prepared.url}` +
							(preview ? `\n\n${preview}${suffix}` : '')
					)
				],
				isError: true
			},
			...meta
		};
	}

	if (base.startsWith('image/')) {
		return {
			result: { content: [{ type: 'image', data: toBase64(bytes), mimeType: base }] },
			...meta
		};
	}
	if (base.startsWith('audio/')) {
		return {
			result: { content: [{ type: 'audio', data: toBase64(bytes), mimeType: base }] },
			...meta
		};
	}

	const isTextual =
		base.includes('json') ||
		base.startsWith('text/') ||
		base.includes('xml') ||
		base.includes('yaml') ||
		base === '';

	if (!isTextual) {
		return {
			result: {
				content: [
					{
						type: 'resource',
						resource: {
							uri: prepared.url,
							mimeType: base || 'application/octet-stream',
							blob: toBase64(bytes)
						}
					}
				]
			},
			...meta
		};
	}

	let text = new TextDecoder().decode(bytes);
	if (text.length > MAX_TEXT_RESULT) {
		text = `${text.slice(0, MAX_TEXT_RESULT)}\n... (truncated)`;
	}

	if (base.includes('json') && text.trim()) {
		try {
			const parsed = JSON.parse(text) as JsonValue;
			const result: CallToolResult = { content: [textBlock(text)] };

			// only claim structured output when it actually matches what the tool advertised
			if (!tool.outputSchema || conformsShallow(parsed, tool.outputSchema)) {
				result.structuredContent = parsed;
			}
			return { result, ...meta };
		} catch {
			// fall through and return the raw text
		}
	}

	return {
		result: { content: [textBlock(text || `${status} ${response.statusText}`)] },
		...meta
	};
}

function describe(error: unknown): string {
	if (error instanceof Error) return error.message;
	return String(error);
}

export { toBase64, fromBase64, encodeBody, conformsShallow };
